"""
DataForSEO se keyword metrics — aur jab wo dastyab na ho to KHAMOSHI se peeche hatna.

── dataforseo.py se farq ────────────────────────────────────────────────────
`dataforseo.py` (purana) sirf search volume laata hai aur nakami par
DataForSEOError PHENKTA hai — us se route 503 deti hai aur user ko keywords
milte hi nahi.

Ye module us se ooper baithta hai aur do cheezein zyada karta hai:

  1. Volume ke ilawa DIFFICULTY aur SEARCH INTENT bhi (DataForSEO Labs ke do
     alag endpoints se).
  2. KABHI raise nahi karta. Har nakami — 402 payment required, 401 auth,
     403 unverified account, timeout, ya koi bhi cheez — `available=False`
     wala natija banti hai. Caller LLM-only mode par chala jata hai aur
     feature chalta rehta hai (Part 2 ka "NEVER breaks").

── Is account ki maujooda haalat (26 Aug 2026 ko naapi gayi) ────────────────
Balance $1.00 hai (khali nahi), MAGAR har data endpoint 403 deta hai:

    40104  "Please verify your account before using the API.
            You can complete verification in the user panel:
            https://app.dataforseo.com/"

Yani abhi LIVE raasta yehi fallback hai. Verification ke baad ye module bina
kisi code change ke asli metrics dene lagega.

── Asli qeematen (appendix/user_data se, brief ke andaze se bohat kam) ──────
    google_ads/search_volume/live         $0.09  PER REQUEST (per keyword NAHI)
    labs/bulk_keyword_difficulty/live     $0.012 + $0.00012/keyword
    labs/search_intent/live               $0.012 + $0.00012/keyword
    labs/related_keywords/live            $0.012 + $0.00012/result

30 keywords ki poori enrichment ≈ $0.12 — yani $1 credit mein ~8 poore run.
"""

import base64
import logging
import os
from dataclasses import dataclass, field

import httpx
from sqlalchemy.orm import Session

from models.seo_result import SEOKeywordMetricCache
from modules.seo.dataforseo import country_name, normalize_country, normalize_keyword

logger = logging.getLogger(__name__)

BASE = "https://api.dataforseo.com/v3"
SEARCH_VOLUME_URL = f"{BASE}/keywords_data/google_ads/search_volume/live"
DIFFICULTY_URL = f"{BASE}/dataforseo_labs/google/bulk_keyword_difficulty/live"
INTENT_URL = f"{BASE}/dataforseo_labs/google/search_intent/live"
RELATED_URL = f"{BASE}/dataforseo_labs/google/related_keywords/live"

TIMEOUT = 45

# Labs endpoints ek request mein 1,000 keywords tak lete hain; Google Ads 700.
MAX_KEYWORDS = 700

SOURCE_VALIDATED = "DataForSEO Validated"
SOURCE_AI = "AI Suggested"


@dataclass
class KeywordMetrics:
    keyword: str
    search_volume: int | None = None
    competition: float | None = None
    competition_index: int | None = None
    cpc: float | None = None
    keyword_difficulty: int | None = None
    search_intent: str | None = None

    @property
    def has_data(self) -> bool:
        return self.search_volume is not None or self.keyword_difficulty is not None


@dataclass
class EnrichmentResult:
    """
    Enrichment ka natija — kamyab ho ya na ho, SHAKAL EK HI rehti hai.

    `available=False` koi error nahi hai; ye ek maloomat hai jo UI tak jati
    hai ("Keywords generated by AI. Connect DataForSEO for search volume data.").
    """
    metrics: dict[str, KeywordMetrics] = field(default_factory=dict)
    available: bool = False
    reason: str | None = None
    related: list[str] = field(default_factory=list)
    cost: float = 0.0
    # Category-level cache ka hisaab kitab (modules/seo/keyword_cache.py bharta
    # hai). Yahan rakha hai taake caller ko ek hi natija object mein sab mile —
    # "kitne keywords cache se aaye, kitne khareede gaye".
    cache_stats: dict = field(default_factory=dict)

    @property
    def source_label(self) -> str:
        return SOURCE_VALIDATED if self.available else SOURCE_AI


# ─────────────────────────────────────────────
#  LOW LEVEL
# ─────────────────────────────────────────────

def is_configured() -> bool:
    return bool((os.getenv("DATAFORSEO_LOGIN") or "").strip()
                and (os.getenv("DATAFORSEO_PASSWORD") or "").strip())


def _auth_header() -> dict:
    login = (os.getenv("DATAFORSEO_LOGIN") or "").strip()
    password = (os.getenv("DATAFORSEO_PASSWORD") or "").strip()
    token = base64.b64encode(f"{login}:{password}".encode()).decode()
    return {"Authorization": f"Basic {token}", "Content-Type": "application/json"}


class _Unavailable(Exception):
    """Andarooni signal: is call se data nahi mila. Bahar kabhi nahi jata."""


def _post(url: str, body: list) -> tuple[list[dict], float]:
    """
    Ek live endpoint call. Har nakami _Unavailable ban jati hai — yahan se
    koi HTTP ya parse exception bahar nahi nikalti.

    Return: (result_items, cost)
    """
    try:
        response = httpx.post(url, json=body, headers=_auth_header(), timeout=TIMEOUT)
    except Exception as exc:                       # timeout, DNS, TLS, sab
        raise _Unavailable(f"network error: {exc}") from exc

    if response.status_code == 402:
        raise _Unavailable("credit exhausted (402 Payment Required)")
    if response.status_code in (401, 403):
        # 403 par body mein asal wajah hoti hai — 40104 "verify your account"
        # is waqt isi raaste se aata hai, aur wo 401 se bilkul alag masla hai.
        detail = ""
        try:
            detail = (response.json() or {}).get("status_message") or ""
        except Exception:
            pass
        raise _Unavailable(f"auth/verification failed ({response.status_code}) {detail}".strip())
    if response.status_code == 429:
        raise _Unavailable("rate limited (429)")
    if response.status_code >= 400:
        raise _Unavailable(f"HTTP {response.status_code}")

    try:
        payload = response.json()
    except Exception as exc:
        raise _Unavailable(f"unreadable response: {exc}") from exc

    status = payload.get("status_code")
    # 20000 = Ok. 40xxx account-level masail (funds, verification) HTTP 200 ke
    # saath bhi aa sakte hain, is liye body ka status alag se dekhna zaroori hai.
    if status is not None and status != 20000:
        raise _Unavailable(f"{status} {payload.get('status_message')}")

    cost = float(payload.get("cost") or 0)
    tasks = payload.get("tasks")
    if not isinstance(tasks, list):
        raise _Unavailable("no tasks in response")

    items: list[dict] = []
    for task in tasks:
        if task.get("status_code", 0) >= 40000:
            raise _Unavailable(f"task {task.get('status_code')} {task.get('status_message')}")
        for result in task.get("result") or []:
            if not isinstance(result, dict):
                continue
            # Labs endpoints natija `result[].items[]` mein dete hain,
            # Google Ads seedha `result[]` mein.
            nested = result.get("items")
            if isinstance(nested, list):
                items.extend(i for i in nested if isinstance(i, dict))
            else:
                items.append(result)
    return items, cost


def _dig(item: dict, *path):
    """Nested key nikaalo, kahin bhi None mile to None."""
    current = item
    for key in path:
        if not isinstance(current, dict):
            return None
        current = current.get(key)
    return current


def _keyword_of(item: dict) -> str | None:
    value = item.get("keyword") or _dig(item, "keyword_data", "keyword")
    return normalize_keyword(str(value)) if value else None


# ─────────────────────────────────────────────
#  CACHE
# ─────────────────────────────────────────────

def _load_cache(db: Session, keywords: list[str], country: str, language: str) -> dict[str, KeywordMetrics]:
    rows = db.query(SEOKeywordMetricCache).filter(
        SEOKeywordMetricCache.normalized_keyword.in_(keywords),
        SEOKeywordMetricCache.country == country.upper(),
        SEOKeywordMetricCache.language == language.lower(),
        SEOKeywordMetricCache.provider == "dataforseo",
    ).all()
    return {
        row.normalized_keyword: KeywordMetrics(
            keyword=row.normalized_keyword,
            search_volume=row.search_volume,
            competition=row.competition,
            competition_index=row.competition_index,
            cpc=row.cpc,
            keyword_difficulty=getattr(row, "keyword_difficulty", None),
            search_intent=getattr(row, "search_intent", None),
        )
        for row in rows
    }


def _save_cache(db: Session, metrics: dict[str, KeywordMetrics], country: str, language: str) -> None:
    """Cache likhna best-effort hai — is par poora keyword flow nahi girna chahiye."""
    try:
        existing = {
            row.normalized_keyword: row
            for row in db.query(SEOKeywordMetricCache).filter(
                SEOKeywordMetricCache.normalized_keyword.in_(list(metrics)),
                SEOKeywordMetricCache.country == country.upper(),
                SEOKeywordMetricCache.language == language.lower(),
                SEOKeywordMetricCache.provider == "dataforseo",
            ).all()
        }
        for keyword, metric in metrics.items():
            if not metric.has_data:
                continue
            row = existing.get(keyword)
            if row is None:
                row = SEOKeywordMetricCache(
                    normalized_keyword=keyword, country=country.upper(),
                    language=language.lower(), provider="dataforseo",
                )
                db.add(row)
            row.search_volume = metric.search_volume
            row.competition = metric.competition
            row.competition_index = metric.competition_index
            row.cpc = metric.cpc
            row.keyword_difficulty = metric.keyword_difficulty
            row.search_intent = metric.search_intent
        db.commit()
    except Exception as exc:
        db.rollback()
        logger.warning("[dataforseo] cache write skipped: %s", exc)


# ─────────────────────────────────────────────
#  PUBLIC API
# ─────────────────────────────────────────────

def enrich_keywords(
    db: Session,
    keywords: list[str],
    country: str,
    language: str = "en",
    *,
    want_related: bool = False,
    always_fresh: set[str] | None = None,
) -> EnrichmentResult:
    """
    Candidates ko asli market data se enrich karo. RAISE KABHI NAHI karta.

    Teen endpoints, teen alag alag faisle: volume na mile to poora enrichment
    nakaam mana jata hai (wahi asal cheez hai jo user maangta hai). Difficulty
    ya intent na milen to baqi data phir bhi wapis jata hai — Labs subscription
    alag hoti hai, aur aadha data na-hone se behtar hai.

    `always_fresh`: wo keywords jinhe local metric cache se SERVE nahi karna,
    chahe wahan maujood hon — brand-specific keywords ("maria b eid
    collection"). Wo har brand ke apne hain aur un ki demand seasons ke saath
    hilti rehti hai, is liye unhe stale data se jawab dena ghalat hota. Likha
    phir bhi jata hai (aana wala run us se bhi shuru kar sake).

    NOTE: filter yahan lagta hai, alag call mein nahi — Google Ads ka search
    volume PER REQUEST charge hota hai ($0.09), per keyword nahi. Do call
    karne se lagat dugni ho jati, ek call mein sab bhejne se nahi.
    """
    always_fresh = always_fresh or set()
    normalized = list(dict.fromkeys(
        normalize_keyword(k) for k in keywords if (k or "").strip()
    ))[:MAX_KEYWORDS]
    if not normalized:
        return EnrichmentResult(available=False, reason="no keywords to enrich")

    if not is_configured():
        return EnrichmentResult(
            available=False,
            reason="DATAFORSEO_LOGIN / DATAFORSEO_PASSWORD not set",
        )

    try:
        country_code = normalize_country(country)
        location = country_name(country_code)
    except Exception as exc:
        return EnrichmentResult(available=False, reason=f"unsupported market: {exc}")

    cacheable = [k for k in normalized if k not in always_fresh]
    cached = _load_cache(db, cacheable, country_code, language) if cacheable else {}
    missing = [k for k in normalized if k not in cached]
    if not missing:
        logger.info("[dataforseo] %d keywords served from cache", len(cached))
        return EnrichmentResult(metrics=cached, available=True, reason="cache")

    metrics: dict[str, KeywordMetrics] = {
        k: KeywordMetrics(keyword=k) for k in missing
    }
    total_cost = 0.0

    # ── 1. Search volume (Google Ads) — ye LAAZMI hai ────────────────────
    try:
        items, cost = _post(SEARCH_VOLUME_URL, [{
            "keywords": missing,
            "location_name": location,
            "language_code": language.lower(),
            "search_partners": False,
        }])
        total_cost += cost
        for item in items:
            keyword = _keyword_of(item)
            if keyword in metrics:
                metrics[keyword].search_volume = item.get("search_volume")
                metrics[keyword].competition_index = item.get("competition_index")
                metrics[keyword].cpc = item.get("cpc")
                competition = item.get("competition")
                # Google Ads kabhi "LOW"/"MEDIUM"/"HIGH" string bhejta hai
                # aur kabhi 0-1 float. Dono ko float par le aao.
                if isinstance(competition, str):
                    competition = {"LOW": 0.15, "MEDIUM": 0.5, "HIGH": 0.85}.get(
                        competition.upper()
                    )
                metrics[keyword].competition = competition
    except _Unavailable as exc:
        logger.warning("DataForSEO credit exhausted, using LLM-only fallback (%s)", exc)
        # Cache mein purana data ho to wo phir bhi qeemti hai.
        if cached:
            return EnrichmentResult(
                metrics=cached, available=True,
                reason=f"partial: live call failed ({exc}), served cache",
            )
        return EnrichmentResult(available=False, reason=str(exc))

    # ── 2. Keyword difficulty (Labs) — na mile to koi baat nahi ──────────
    try:
        items, cost = _post(DIFFICULTY_URL, [{
            "keywords": missing,
            "location_name": location,
            "language_code": language.lower(),
        }])
        total_cost += cost
        for item in items:
            keyword = _keyword_of(item)
            if keyword in metrics:
                value = item.get("keyword_difficulty")
                if value is None:
                    value = _dig(item, "keyword_properties", "keyword_difficulty")
                metrics[keyword].keyword_difficulty = value
    except _Unavailable as exc:
        logger.info("[dataforseo] difficulty unavailable, deriving from competition (%s)", exc)

    # ── 3. Search intent (Labs) — na mile to heuristic chalega ───────────
    try:
        items, cost = _post(INTENT_URL, [{
            "keywords": missing,
            "language_code": language.lower(),
        }])
        total_cost += cost
        for item in items:
            keyword = _keyword_of(item)
            if keyword in metrics:
                label = _dig(item, "keyword_intent", "label") or item.get("intent")
                if label:
                    metrics[keyword].search_intent = str(label).lower()
    except _Unavailable as exc:
        logger.info("[dataforseo] search intent unavailable, using heuristic (%s)", exc)

    related: list[str] = []
    if want_related and missing:
        related = fetch_related(missing[0], country_code, language)

    _save_cache(db, metrics, country_code, language)
    metrics.update(cached)

    logger.info(
        "[dataforseo] enriched %d keywords for %s (cost $%.4f)",
        len(missing), country_code, total_cost,
    )
    return EnrichmentResult(
        metrics=metrics, available=True, reason=None,
        related=related, cost=total_cost,
    )


def fetch_related(seed: str, country: str, language: str = "en", limit: int = 20) -> list[str]:
    """
    Labs se related keywords — wo terms jo LLM ne socha hi nahi.
    Nakami par khali list; ye feature optional hai.
    """
    try:
        location = country_name(normalize_country(country))
        items, _ = _post(RELATED_URL, [{
            "keyword": normalize_keyword(seed),
            "location_name": location,
            "language_code": language.lower(),
            "depth": 1,
            "limit": limit,
        }])
    except _Unavailable as exc:
        logger.info("[dataforseo] related keywords unavailable (%s)", exc)
        return []

    out = []
    for item in items:
        keyword = _keyword_of(item)
        if keyword and keyword != normalize_keyword(seed):
            out.append(keyword)
    return out[:limit]


def account_status() -> dict:
    """
    Chhota health check — UI/logs ke liye "DataForSEO kis haal mein hai".
    Ye endpoint FREE hai (cost 0), is liye ise call karna mehnga nahi.
    """
    if not is_configured():
        return {"configured": False, "usable": False,
                "reason": "DATAFORSEO_LOGIN / DATAFORSEO_PASSWORD not set"}
    try:
        response = httpx.get(f"{BASE}/appendix/user_data",
                             headers=_auth_header(), timeout=TIMEOUT)
        payload = response.json()
        if payload.get("status_code") != 20000:
            return {"configured": True, "usable": False,
                    "reason": payload.get("status_message")}
        result = payload["tasks"][0]["result"]
        result = result[0] if isinstance(result, list) else result
        money = result.get("money") or {}
        return {
            "configured": True,
            "usable": True,
            "balance": money.get("balance"),
            "reason": None,
        }
    except Exception as exc:
        return {"configured": True, "usable": False, "reason": str(exc)}
