import LegalPage from '@/components/legal/LegalPage'

export const metadata = {
  title: 'Privacy Policy — BrandWave',
  description:
    'How BrandWave collects, uses, stores and shares data for its AI marketing automation platform.',
}

/* Ek hi jagah se badlo — neeche do jagah istemal hota hai. */
const CONTACT = 'laibslb2004@gmail.com'

export default function Privacy() {
  return (
    <LegalPage
      title="Privacy Policy"
      updated="5 September 2026"
      lede="BrandWave is an AI marketing automation platform for Shopify merchants. This policy explains exactly what we collect, why, who processes it on our behalf, and how you remove it."
    >
      <h2>1. Who we are</h2>
      <p>
        BrandWave (&ldquo;we&rdquo;, &ldquo;the service&rdquo;) provides catalogue scraping,
        sentiment analysis, SEO tooling, ad generation and a support chatbot for online
        stores. Questions about this policy or your data go to{' '}
        <a href={`mailto:${CONTACT}`}>{CONTACT}</a>.
      </p>

      <h2>2. What we collect</h2>

      <h3>Account information</h3>
      <ul>
        <li>Email address and password, or your Google account identity if you sign in with Google</li>
        <li>Business name and role</li>
        <li>Optional profile details you enter: full name, phone number, avatar, timezone, notification preferences</li>
      </ul>
      <p>
        Passwords are never stored by us. Authentication is handled by a specialist identity
        provider which stores only a cryptographic hash — we cannot read your password.
      </p>

      <h3>Store data</h3>
      <ul>
        <li>The store URL you submit</li>
        <li>Publicly available catalogue data scraped from that store: product names, descriptions, prices, images and collections</li>
        <li>Publicly available customer reviews used for sentiment analysis</li>
      </ul>
      <p>
        We only scrape pages that are publicly accessible without logging in. We do not collect
        your customers&rsquo; payment details, addresses or order history.
      </p>

      <h3>Content you generate</h3>
      <ul>
        <li>Generated image and video advertisements, and the prompts and settings used to create them</li>
        <li>SEO audits, keyword reports and blog drafts</li>
        <li>Sentiment analysis results</li>
        <li>Conversations with the AI assistant</li>
      </ul>

      <h3>Chatbot conversations</h3>
      <p>
        If you embed the BrandWave chatbot widget on your store, we store the messages
        exchanged between your visitors and the bot, plus an anonymous session identifier.
        This lets you review conversations and lets the bot keep context. Visitors are not
        asked to create an account and we do not track them across other websites.
      </p>

      <h2>3. How we use it</h2>
      <ul>
        <li>To provide the features you request — scraping, analysis, generation</li>
        <li>To authenticate you and keep you signed in</li>
        <li>To send transactional email: address verification and password reset</li>
        <li>To debug failures and keep the service running</li>
      </ul>
      <p>
        <strong>We do not sell your data, and we do not use it for advertising.</strong> We do
        not use your catalogue or conversations to train our own models.
      </p>

      <h2>4. Third parties that process data for us</h2>
      <p>
        Running the service requires working with specialist providers. They fall into these
        categories, and each receives only the data its function requires:
      </p>
      <ul>
        <li><strong>Authentication</strong> — verifying your identity and keeping you signed in</li>
        <li><strong>Cloud hosting and infrastructure</strong> — running the application and storing generated media</li>
        <li><strong>Managed database hosting</strong> — storing your account and store data</li>
        <li><strong>AI model providers</strong> — generating advertising copy, images and video from the prompts and product images you supply</li>
        <li><strong>Search and indexing</strong> — making documents you upload searchable by the chatbot</li>
        <li><strong>SEO data providers</strong> — keyword volumes and ranking information for your store</li>
      </ul>
      <p>
        These providers process data on our instructions and for no other purpose. A current
        list of the specific providers we use is available on request at{' '}
        <a href={`mailto:${CONTACT}`}>{CONTACT}</a>.
      </p>
      <p>
        Data is stored in the <strong>United States</strong>. If you are outside the US, using
        BrandWave means your data is transferred there.
      </p>

      <h2>5. AI-generated content</h2>
      <p>
        Advertisements produced by BrandWave are generated by AI models. You are responsible
        for ensuring any advertisement you publish complies with the advertising and
        AI-disclosure rules that apply in your market and on the platform you publish to.
      </p>

      <h2>6. Retention and deletion</h2>
      <p>
        We keep your data for as long as your account exists. BrandWave includes a
        <strong> delete account</strong> function in your profile settings, which removes your
        authentication record, profile, brand profiles, scraped catalogues, generated
        advertisements, SEO results and chatbot data.
      </p>
      <p>
        Deletion is immediate in our systems. Copies held in provider logs or backups may
        persist for a short period according to each provider&rsquo;s own retention schedule.
        Content already sent to an AI provider for generation is subject to that
        provider&rsquo;s policy and cannot be recalled by us.
      </p>

      <h2>7. Cookies and browser storage</h2>
      <p>
        We use cookies only to keep you signed in — your session token. We also use
        your browser&rsquo;s local storage for convenience: remembering a selected brand, a
        chatbot session id, and cached results so pages load faster.
      </p>
      <p>
        <strong>We use no advertising or third-party tracking cookies</strong>, and no
        analytics that profile you across sites.
      </p>

      <h2>8. Your rights</h2>
      <ul>
        <li><strong>Access</strong> — everything we hold is visible in the dashboard</li>
        <li><strong>Correction</strong> — edit your profile at any time</li>
        <li><strong>Deletion</strong> — remove your account and its data from profile settings</li>
        <li><strong>Export</strong> — email us and we will provide your data in a machine-readable form</li>
      </ul>
      <p>
        Depending on where you live you may have further rights under the GDPR or similar law.
        Contact us at <a href={`mailto:${CONTACT}`}>{CONTACT}</a> to exercise them.
      </p>

      <h2>9. Security</h2>
      <ul>
        <li>All traffic is encrypted in transit with HTTPS (TLS)</li>
        <li>Passwords are hashed by our authentication provider and never visible to us</li>
        <li>The database is reachable only over an encrypted connection</li>
        <li>API access requires a signed token verified on every request</li>
      </ul>
      <p>
        No system is perfectly secure. If you believe you have found a vulnerability, please
        report it to <a href={`mailto:${CONTACT}`}>{CONTACT}</a> rather than disclosing it
        publicly.
      </p>

      <h2>10. Children</h2>
      <p>
        BrandWave is a business tool and is not directed at anyone under 16. We do not
        knowingly collect data from children.
      </p>

      <h2>11. Changes</h2>
      <p>
        If this policy changes materially we will update the date at the top of this page.
        Continuing to use the service after a change means you accept it.
      </p>

    </LegalPage>
  )
}
